{"name": "Ошибка при создании курьера с существующим логином", "status": "passed", "start": 1743008801855, "stop": 1743008802198, "uuid": "2036a433-51b5-4737-bdae-e8112144859a", "historyId": "89579da75853808ed683d1fda86505ab", "testCaseId": "89579da75853808ed683d1fda86505ab", "fullName": "tests.test_create_courier.TestCreateCourier#test_same_login_two_couriers_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "Natalia_Ivanova"}, {"name": "thread", "value": "48168-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}