{"name": "Ошибка при попытке создания двух одинаковых курьеров", "status": "passed", "start": 1743008800420, "stop": 1743008800855, "uuid": "d75aa854-a6bd-42e2-bbbe-7e2d00abead4", "historyId": "eefe4d29c7c2be46d49aa01fdbcd7960", "testCaseId": "eefe4d29c7c2be46d49aa01fdbcd7960", "fullName": "tests.test_create_courier.TestCreateCourier#test_creating_two_equal_couriers_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "Natalia_Ivanova"}, {"name": "thread", "value": "48168-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}